<?php

use Illuminate\Database\Seeder;

use App\Models\Crawlers\MediaCrawler;

class MediaCrawlersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $items = [
           [
                'name' => 'PLATINONLINE',
                'site' => 'https://www.platinonline.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h4',
                'off_limit' => 255,
            ],
            [
                'name' => 'İNTERNETHABER',
                'site' => 'http://www.internethaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{7,9})h\.htm',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'SABAHAKTÜEL',
                'site' => 'https://www.sabah.com.tr',
                'base' => 'aktuel',
                'url_pattern' => '(\b(?!yazarlar|album))([a-z0-9-]{4,24}\/)?([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.pageTitle',
                'selector_description' => 'h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'TEKNOKULİS',
                'site' => 'http://www.teknokulis.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.pageTitle',
                'selector_description' => 'h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'MARKETINGTÜRKİYE',
                'site' => 'http://www.marketingturkiye.com.tr',
                'base' => 'haberler',
                'url_pattern' => 'haberler\/([a-z0-9-]{24,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.td-post-content > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'MEDIACAT',
                'site' => 'https://mediacat.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{24,128})(?=\/")',
                'selector_title' => 'h1.main-title',
                'selector_description' => '.excerpt',
                'off_limit' => 255,
            ],
            [
                'name' => 'OTOHABER',
                'site' => 'http://www.otohaber.com.tr',
                'base' => '/',
                'url_pattern' => 'haberler\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => 'h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'EUROVİZYON',
                'site' => 'http://www.eurovizyon.co.uk',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{5,9})\.html',
                'selector_title' => '.panel-title h1',
                'selector_description' => '.panel-title p',
                'off_limit' => 255,
            ],
            [
                'name' => 'NTV',
                'site' => 'https://www.ntv.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=href="\/)([a-z0-9-]{4,24})\/([a-z0-9-]{4,128}),([a-zA-Z0-9-_]{22})(?=")',
                'selector_title' => 'h1',
                'selector_description' => 'article > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'SPUTNIKNEWS',
                'site' => 'https://tr.sputniknews.com',
                'base' => '/',
                'url_pattern' => '(\b(?!infografik))([a-z0-9_-]{4,24})\/\d{4}\d{2}\d{2}(\d{10})-([a-z0-9-]{10,128})',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '.b-article__lead > p',
                'off_limit' => 255,
            ],
            [
                'name' => 'JURNAL',
                'site' => 'http://www.jurnal.net',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => 'blockquote',
                'off_limit' => 255,
            ],
            [
                'name' => 'SHIFTDELETE',
                'site' => 'https://shiftdelete.net',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{24,128})(?=")',
                'selector_title' => 'h1',
                'selector_description' => '#post_detail_content p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'YAZETE',
                'site' => 'http://www.yazete.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'NTVSPOR',
                'site' => 'https://www.ntvspor.net',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-([a-z0-9]{16,32})',
                'selector_title' => 'h1',
                'selector_description' => '.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'OBJEKTİFHABER',
                'site' => 'http://www.objektifhaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{6,9})-haber',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'p[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'T24',
                'site' => 'http://t24.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})\,(\d{6,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.top-context > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'TOBB',
                'site' => 'https://tobb.org.tr',
                'base' => 'Sayfalar/Arsiv.php?lst=Haberler',
                'url_pattern' => 'Sayfalar\/Detay\.php\?rid\=(\d{4,9})\&lst\=Haberler',
                'selector_title' => '#subpage-content > h3.title',
                'selector_description' => '#subpage-content > .box-content-container:first-child',
                'off_limit' => 10,
            ],
            [
                'name' => 'GİRİŞİMHABER',
                'site' => 'http://www.girisimhaber.com',
                'base' => '/',
                'url_pattern' => 'post\/(\d{4})\/(\d{2})\/(\d{2})\/([a-zA-Z0-9-]{4,128})\.aspx',
                'selector_title' => '#post_title',
                'selector_description' => '#entry p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'FOTOSPOR',
                'site' => 'http://www.fotospor.com',
                'base' => '/',
                'url_pattern' => 'haber-([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h3[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'NETPANO',
                'site' => 'http://www.netpano.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{24,128})(?=\/")',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.td-post-content p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'GOAL',
                'site' => 'https://www.goal.com',
                'base' => 'tr',
                'url_pattern' => 'tr\/haber\/([a-z0-9-]{4,128})\/([a-z0-9]{4,32})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'BLOOMBERGHT',
                'site' => 'https://www.bloomberght.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/haber\/\d{7,9}-([a-z0-9-]{4,24})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'DİRİLİŞPOSTASI',
                'site' => 'https://www.dirilispostasi.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-([a-z0-9]{24})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'SONSÖZ',
                'site' => 'https://sonsoz.com.tr',
                'base' => 'feed',
                'url_pattern' => '([a-z0-9-]{24,128})(?=\/)',
                'selector_title' => 'h1.entry-title',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'HABERLER',
                'site' => 'https://www.haberler.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{8,9})-haberi',
                'selector_title' => 'h1#haber_baslik',
                'selector_description' => 'h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'DÖRDÜNCÜKUVVET',
                'site' => 'http://www.dorduncukuvvet.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{24,128})(?=\/")',
                'selector_title' => '[itemprop="headline"]',
                'selector_description' => '.entry-content p:nth-child(1)',
                'off_limit' => 255,
            ],
            [
                'name' => 'MİLLİGAZETE',
                'site' => 'https://www.milligazete.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{7,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'p[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'SAHADAN',
                'site' => 'https://www.sahadan.com',
                'base' => 'haberler/arsiv',
                'url_pattern' => '([a-z0-9-]{4,24})\/haber\/([a-z0-9-]{4,128})\/([a-z0-9]{4,32})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'SİNEMALAR',
                'site' => 'https://www.sinemalar.com',
                'base' => 'sinemahaberleri',
                'url_pattern' => 'haber\/(\d{4,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => '[itemprop="articleBody"] p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'YENİASIR',
                'site' => 'https://www.yeniasir.com.tr',
                'base' => '/',
                'url_pattern' => '(([a-z0-9-]{4,24})\/)?([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.detail-title',
                'selector_description' => 'p.detail-spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'PRESSTÜRK',
                'site' => 'http://www.pressturk.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})\/(\d{5,9})',
                'selector_title' => '.haber-detay > div:nth-child(2)',
                'selector_description' => '.haber-detay > div:nth-child(3)',
                'off_limit' => 255,
            ],
            [
                'name' => 'GAZETEYENİYÜZYIL',
                'site' => 'http://www.gazeteyeniyuzyil.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{6,9})\.html',
                'selector_title' => 'h3.title',
                'selector_description' => 'p.lead',
                'off_limit' => 100,
            ],
            [
                'name' => 'GERÇEKGÜNDEM',
                'site' => 'http://www.gercekgundem.com',
                'base' => '/',
                'url_pattern' => '(\b(?!posts))([a-z0-9-]{4,128})\/(\d{5,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.article-title',
                'selector_description' => '.article-excerpt',
                'off_limit' => 255,
            ],
            [
                'name' => 'GAZETECİLER',
                'site' => 'http://www.gazeteciler.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'TAKVİM',
                'site' => 'https://www.takvim.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{10,128})',
                'selector_title' => 'h1#haberTitle',
                'selector_description' => 'h2#haberSpot',
                'off_limit' => 255,
            ],
            [
                'name' => 'MEMURLAR',
                'site' => 'https://www.memurlar.net',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{6,9})\/([a-z0-9-]{4,128})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '[itemprop="description"]',
                'off_limit' => 10,
            ],
            [
                'name' => 'EVRENSEL',
                'site' => 'https://www.evrensel.net',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{6,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => '.spot > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'NETGAZETE',
                'site' => 'http://www.netgazete.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})(?=")',
                'selector_title' => 'h1',
                'selector_description' => 'p.haber-spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'BIGPARA',
                'site' => 'http://bigpara.hurriyet.com.tr',
                'base' => '/',
                'url_pattern' => 'haberler\/([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})_ID(\d{7,9})',
                'selector_title' => 'h1.news-detail-title',
                'selector_description' => '.tag-content > p:first-child',
                'off_limit' => 10,
            ],
            [
                'name' => 'İLERİHABER',
                'site' => 'http://ilerihaber.org',
                'base' => '/',
                'url_pattern' => 'icerik\/([a-z0-9-]{10,128})-(\d{5,9})\.html',
                'selector_title' => '.waypoint > h1',
                'selector_description' => '.waypoint > h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'ULUSALKANAL',
                'site' => 'http://www.ulusalkanal.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{6,9})\.html',
                'selector_title' => 'h2',
                'selector_description' => 'h3',
                'off_limit' => 255,
            ],
            [
                'name' => 'TRTSPOR',
                'site' => 'https://www.trtspor.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,24})\/([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => '.section > h2',
                'selector_description' => '.news-detail p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'TELEVİZYONGAZETESİ',
                'site' => 'https://televizyongazetesi.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})\/(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => '#content-area > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'MYNETSPOR',
                'site' => 'https://www.mynet.com',
                'base' => 'spor',
                'url_pattern' => '([a-z0-9-]{10,128})-(\d{6,9})-myspor',
                'selector_title' => 'h1.detail-post-title',
                'selector_description' => 'h2.detail-post-spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'MEDYAALEMİ',
                'site' => 'http://www.medyaalemi.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{4,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'BİRGÜN',
                'site' => 'https://www.birgun.net',
                'base' => '/',
                'url_pattern' => 'haber-detay\/([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'article.haber-detay .title',
                'selector_description' => '.body > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'İHA',
                'site' => 'http://www.iha.com.tr',
                'base' => '/',
                'url_pattern' => 'haber-([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'TÜRKTIME',
                'site' => 'http://www.turktime.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => '#haberdetaybaslik > h1',
                'selector_description' => '#haberdetaybaslik > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'MEPANEWS',
                'site' => 'https://www.mepanews.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{10,128})-(\d{5,9})h\.htm',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'YENİSÖZ',
                'site' => 'http://www.gazetevatan.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{7,9})-([a-z0-9-]{4,24})',
                'selector_title' => '.content h1',
                'selector_description' => '.content h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'SÜPERHABER',
                'site' => 'https://www.superhaber.tv',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-haber-(\d{6,9})',
                'selector_title' => '.news-detail h1',
                'selector_description' => '.news-detail h2:last-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'MİLATGAZETESİ',
                'site' => 'https://www.milatgazetesi.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})([a-z0-9-]{4,24})\/haber-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'p.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'ONEDİO',
                'site' => 'https://onedio.com',
                'base' => 'haberler',
                'url_pattern' => 'haber\/([a-z0-9-]{10,128})-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => '.text > h3',
                'off_limit' => 255,
            ],
            [
                'name' => 'TÜRKİYEGAZETESİ',
                'site' => 'http://www.turkiyegazetesi.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar))([a-z0-9-]{4,24})\/(\d{6,9})\.aspx',
                'selector_title' => 'h1',
                'selector_description' => 'h2.article_abstract',
                'off_limit' => 255,
            ],
            [
                'name' => 'RUDAW',
                'site' => 'http://www.rudaw.net',
                'base' => 'Turkish',
                'url_pattern' => 'turkish\/([a-z0-9-]{4,24})\/(\d{9,10})',
                'selector_title' => 'h3.articleTitle',
                'selector_description' => '.textContent > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'KARGOHABER',
                'site' => 'http://www.kargohaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{4,9})h\.htm',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'KHA',
                'site' => 'http://www.kha.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{5,9})h\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'p.introduction',
                'off_limit' => 255,
            ],
            [
                'name' => 'CHIP',
                'site' => 'https://www.chip.com.tr',
                'base' => 'haber',
                'url_pattern' => 'haber\/([a-z0-9-]{10,128})_(\d{5,9})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'p[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'MEDYASPOR',
                'site' => 'http://medyaspor.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})-(\d{5,9})',
                'selector_title' => 'h1',
                'selector_description' => 'p.lead',
                'off_limit' => 255,
            ],
            [
                'name' => 'ŞAMDAN',
                'site' => 'http://www.samdan.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=href\="\/)([a-z0-9-]{4,128})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})(?=")',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'BEINSPORTS',
                'site' => 'http://tr.beinsports.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})',
                'selector_title' => 'h2#NewsTitle',
                'selector_description' => '[itemprop="articleBody"] div:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'SONSAYFA',
                'site' => 'http://www.sonsayfa.com',
                'base' => '/',
                'url_pattern' => 'Haberler\/([a-zA-Z0-9-]{4,24})\/([a-zA-Z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => '.news-detail h2',
                'selector_description' => '.news-detail p.brief',
                'off_limit' => 255,
            ],
            [
                'name' => 'FUTBOLSAYFASI',
                'site' => 'https://www.futbolsayfasi.net',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{5,9})\.html',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'DİKEN',
                'site' => 'http://www.diken.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=\.com.tr\/)([a-z0-9-]{16,})(?=\/)',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.entry-content',
                'off_limit' => 255,
            ],
            [
                'name' => 'AYDINLIK',
                'site' => 'https://www.aydinlik.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-([a-z0-9-]{4,24})([a-z0-9-]{4,24})(\d{4})([-]\d{1})',
                'selector_title' => 'h1.author_title',
                'selector_description' => '.white p:nth-child(2)',
                'off_limit' => 255,
            ],
            [
                'name' => 'FOTOMAÇ',
                'site' => 'https://www.fotomac.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=href="\/(?!album))([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1#NewsTitle',
                'selector_description' => 'h2#NewsSpot',
                'off_limit' => 255,
            ],
            [
                'name' => 'BEYAZPERDE',
                'site' => 'http://www.beyazperde.com',
                'base' => 'haberler-dosyalar',
                'url_pattern' => 'haberler\/(diziler|filmler)\/haberler-(\d{5,9})',
                'selector_title' => '[itemprop="headline"]',
                'selector_description' => '#article-content > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'HÜRHABER',
                'site' => 'http://www.hurhaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.dsag > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'MYNETHABER',
                'site' => 'http://www.mynet.com',
                'base' => 'haber',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{10,12})',
                'selector_title' => 'h1.detail-post-title',
                'selector_description' => 'h2.detail-post-spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'DOĞRUHABER',
                'site' => 'https://dogruhaber.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{6,9})-([a-z0-9-]{4,128})\/',
                'selector_title' => 'h1',
                'selector_description' => 'article > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'SONDAKİKA',
                'site' => 'https://www.sondakika.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})-(\d{8,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'ODATV',
                'site' => 'https://www.odatv.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{7,9})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'FİKRİYAT',
                'site' => 'https://www.fikriyat.com',
                'base' => '/',
                'url_pattern' => '(?<=href\="\/)([a-z0-9-]{4,128})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})(?=")',
                'selector_title' => 'h1.post-title',
                'selector_description' => '.post-body > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'YENİAKİT',
                'site' => 'http://www.yeniakit.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'HABER7',
                'site' => 'http://www.haber7.com',
                'base' => '/',
                'url_pattern' => '(\b(?!advertorial|yazarlar))([a-z0-9-]{4,24})\/haber\/(\d{7,9})-([a-z0-9-]{4,128})',
                'selector_title' => 'h1.title',
                'selector_description' => 'h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'SOL',
                'site' => 'http://haber.sol.org.tr',
                'base' => 'anasayfa',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1#page-title',
                'selector_description' => '.singlenews-spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'POSTA',
                'site' => 'http://www.posta.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})(-(\b(?!video)))?-(\d{7,9})',
                'selector_title' => 'h1.news-detail__info__title',
                'selector_description' => 'h2.news-detail__info__spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'SPORX',
                'site' => 'http://www.sporx.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{10,128})-([A-Z0-9]){14}',
                'selector_title' => 'h1#habertitle',
                'selector_description' => 'h2#haberheadline',
                'off_limit' => 255,
            ],
            [
                'name' => 'KARAR',
                'site' => 'http://www.karar.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1.title',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'URFANATİK',
                'site' => 'http://www.urfanatik.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{5,9})\.html',
                'selector_title' => 'h1',
                'selector_description' => 'p.lead',
                'off_limit' => 255,
            ],
            [
                'name' => 'DONANIMHABER',
                'site' => 'https://www.donanimhaber.com',
                'base' => '/',
                'url_pattern' => '([a-zA-Z0-9-]{4,128})--(\d{6,9})',
                'selector_title' => 'h1.post-baslik',
                'selector_description' => '.surmanset',
                'off_limit' => 255,
            ],
            [
                'name' => 'MEDYAFARESİ',
                'site' => 'http://www.medyafaresi.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => '.news > h1',
                'selector_description' => '.news > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'DEMOKRATHABER',
                'site' => 'https://www.demokrathaber.org',
                'base' => '/',
                'url_pattern' => '(\b(?!tarih))([a-z0-9-]{4,24})\/([a-z0-9-]{10,128})-h(\d{6,9})\.html',
                'selector_title' => '.panel-title > h1',
                'selector_description' => '.panel-title > p',
                'off_limit' => 255,
            ],
            [
                'name' => 'ARKEOLOJİKHABER',
                'site' => 'https://www.arkeolojikhaber.com',
                'base' => '/',
                'url_pattern' => 'haber-([a-z0-9-]{4,128})-(\d{5,9})',
                'selector_title' => '.entry-header > h1.entry-title',
                'selector_description' => '.entry-content p:nth-child(1)',
                'off_limit' => 255,
            ],
            [
                'name' => 'WEBTEKNO',
                'site' => 'http://www.webtekno.com',
                'base' => 'haber',
                'url_pattern' => '([a-z0-9-]{10,128})-h(\d{5,9})\.html',
                'selector_title' => 'h1[itemprop="headline"] a',
                'selector_description' => '[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'YAKINPLAN',
                'site' => 'https://yakinplan.com',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.td-post-content > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'TÜRKİYEHABERAJANSI',
                'site' => 'http://www.turkiyehaberajansi.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'CNNTÜRK',
                'site' => 'https://www.cnnturk.com',
                'base' => '/',
                'url_pattern' => '(?<=href="\/)([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})(?=")',
                'selector_title' => 'h1.detail-title',
                'selector_description' => 'h2.detail-description',
                'off_limit' => 255,
            ],
            [
                'name' => 'GAZETEVATAN',
                'site' => 'http://www.gazetevatan.com',
                'base' => '/',
                'url_pattern' => '((?!.*yazar-yazisi)[a-z0-9-]{4,128})-(\d{7,9})-([a-z0-9-]{4,24})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'YENİŞAFAK',
                'site' => 'https://www.yenisafak.com',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'ÖNCEVATAN',
                'site' => 'https://www.oncevatan.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{6,9})\.html',
                'selector_title' => 'h3.title',
                'selector_description' => 'p.lead',
                'off_limit' => 255,
            ],
            [
                'name' => 'AJANSHABER',
                'site' => 'http://www.ajanshaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-haber-(\d{6,9})',
                'selector_title' => 'header > h1',
                'selector_description' => 'header > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'BEYAZGAZETE',
                'site' => 'http://beyazgazete.com',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{4})\/(\d{1,2})\/(\d{1,2})\/([a-z0-9-]{4,128})-(\d{7,9})\.html',
                'selector_title' => 'h1.title',
                'selector_description' => 'p.description',
                'off_limit' => 255,
            ],
            [
                'name' => 'OCAKMEDYA',
                'site' => 'http://www.ocakmedya.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.td-post-content > p:first-child',
                'off_limit' => 255,
            ],
            [
                'name' => 'BBC',
                'site' => 'https://www.bbc.com',
                'base' => 'turkce',
                'url_pattern' => '(\b(?!gettyimages|-))turkce\/([a-z0-9-]{10,128})-(\d{8,9})',
                'selector_title' => 'h1.story-body__h1',
                'selector_description' => 'p.story-body__introduction',
                'off_limit' => 255,
            ],
            [
                'name' => 'HABERTÜRK',
                'site' => 'http://www.haberturk.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{2,128})-(\d{7,8})(-[a-z0-9-]{2,24})?',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'YURTGAZETESİ',
                'site' => 'http://www.yurtgazetesi.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{5,9})\.html',
                'selector_title' => 'h3.title',
                'selector_description' => 'p.lead',
                'off_limit' => 255,
            ],
            [
                'name' => 'GAZETENEHABER',
                'site' => 'http://www.gazetenehaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})\/(\d{5,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'ASPOR',
                'site' => 'https://www.aspor.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'TIMETURK',
                'site' => 'https://www.timeturk.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})\/haber-(\d{6,9})',
                'selector_title' => '.content > h1',
                'selector_description' => '.content > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'AA',
                'site' => 'https://www.aa.com.tr',
                'base' => 'tr',
                'url_pattern' => 'tr\/([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})\/(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => '.lead',
                'off_limit' => 255,
            ],
            [
                'name' => 'DHA',
                'site' => 'https://www.dha.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!foto-galeri|video|english))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})\/haber-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => '.news-body > p.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'DÜNYA',
                'site' => 'https://www.dunya.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-haberi-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'MİLLİYET',
                'site' => 'http://www.milliyet.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar|album))([a-z0-9-]{4,128})-(\d{7,9})(?=\/)',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'TGRTHABER',
                'site' => 'http://www.tgrthaber.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!fotogaleri))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})(?=")',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2.haber-spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'YENİASYA',
                'site' => 'http://www.yeniasya.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!video|yazar))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})_(\d{6,9})',
                'selector_title' => '.head > h2',
                'selector_description' => '.details > .intro',
                'off_limit' => 255,
            ],
            [
                'name' => 'ANADOLUGAZETESİ',
                'site' => 'http://www.anadolugazetesi.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{10,128})-(\d{6,9})\.html',
                'selector_title' => '.Baslik > h1',
                'selector_description' => '.ozet > h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'HTKULÜP',
                'site' => 'https://htkulup.haberturk.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/haber\/(\d{7,9})-([a-z0-9-]{10,128})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'HABERVAKTİM',
                'site' => 'https://www.habervaktim.com',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{6,9})\/([a-z0-9-]{4,128})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '.short_content',
                'off_limit' => 255,
            ],
            [
                'name' => 'DÖVİZ',
                'site' => 'https://haber.doviz.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{10,128})\/(\d{6,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.left-column p',
                'off_limit' => 255,
            ],
            [
                'name' => 'HABERGAZETESİ',
                'site' => 'http://www.habergazetesi.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{7,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'AHABER',
                'site' => 'https://www.ahaber.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=href="\/)([a-z0-9-]{4,24})\/\d{4}\/\d{2}\/\d{2}\/([a-z0-9-]{4,128})',
                'selector_title' => '.detailLeftFrame h1',
                'selector_description' => '.detailLeftFrame h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'YENİMESAJ',
                'site' => 'http://www.yenimesaj.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-H(\d{6,9})\.htm',
                'selector_title' => 'h1.h1',
                'selector_description' => '.haber > div:nth-child(2)',
                'off_limit' => 255,
            ],
            [
                'name' => 'EURONEWS',
                'site' => 'https://tr.euronews.com',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => '.c-article-content',
                'off_limit' => 255,
            ],
            [
                'name' => 'YENİÇAĞ',
                'site' => 'http://www.yenicaggazetesi.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{6,9})h\.htm',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'MEDYARADAR',
                'site' => 'http://www.medyaradar.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{16,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'BİANET',
                'site' => 'http://bianet.org',
                'base' => '/',
                'url_pattern' => 'bianet\/([a-z0-9-]{4,128})\/(\d{6,9})-([a-z0-9-]{4,128})',
                'selector_title' => '.post_text_container > a',
                'selector_description' => '.desc',
                'off_limit' => 255,
            ],
            [
                'name' => 'SÖZCÜ',
                'site' => 'https://www.sozcu.com.tr',
                'base' => '/',
                'url_pattern' => '(\d{4})\/([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'AKŞAM',
                'site' => 'http://www.aksam.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})\/haber-(\d{6,9})',
                'selector_title' => '.newsdetailwrap h1',
                'selector_description' => '.newsdetailwrap h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'ENSONHABER',
                'site' => 'http://www.ensonhaber.com',
                'base' => '/',
                'url_pattern' => '((?!.*-kimdir)[a-z0-9-]{10,128})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'HABER3',
                'site' => 'https://www.haber3.com',
                'base' => '/',
                'url_pattern' => '(\b(?!foto-galeri))([a-z0-9-]{4,24}\/)?([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'CUMHURİYET',
                'site' => 'http://www.cumhuriyet.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,24})\/(\d{7,9})\/([a-zA-Z0-9-_]{4,128})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.news-short',
                'off_limit' => 255,
            ],
            [
                'name' => 'STAR',
                'site' => 'http://www.star.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-haber-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'TRTHABER',
                'site' => 'http://www.trthaber.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'p[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'F5HABER',
                'site' => 'https://www.f5haber.com',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar|yazar))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 100,
            ],
            [
                'name' => 'HÜRRİYET',
                'site' => 'http://www.hurriyet.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=href\="\/)([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{8,9})(?=")',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 100,
            ],
            [
                'name' => 'MEDYALOJİ',
                'site' => 'https://www.medyaloji.net',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})_(\d{8,9})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '.articleTitle > div',
                'off_limit' => 10,
            ],
            [
                'name' => 'GAZETEPORT',
                'site' => 'http://gazeteport.com',
                'base' => '/',
                'url_pattern' => '(\d{4})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.entry p:first-child',
                'off_limit' => 10,
            ],
            [
                'name' => 'GAZETEDUVAR',
                'site' => 'https://www.gazeteduvar.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => '.single-post h2',
                'selector_description' => 'span.subtitle',
                'off_limit' => 255,
            ],
            [
                'name' => 'ORTADOĞUGAZETESİ',
                'site' => 'http://www.ortadogugazetesi.net',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{5,9})\.html',
                'selector_title' => '.content h1',
                'selector_description' => '.content strong:first-child',
                'off_limit' => 10,
            ],
            [
                'name' => 'HABERİYAKALA',
                'site' => 'http://www.haberiyakala.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{6,9})-haber',
                'selector_title' => 'h1.news-title',
                'selector_description' => 'h2.news-desc',
                'off_limit' => 255,
            ],
            [
                'name' => 'KAMUAJANS',
                'site' => 'http://www.kamuajans.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{10,128})-h(\d{6,9})\.html',
                'selector_title' => 'h1',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'ANAYURTGAZETESİ',
                'site' => 'http://www.anayurtgazetesi.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-zA-Z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'FANATİK',
                'site' => 'https://www.fanatik.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar))([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1.news-detail__info__title',
                'selector_description' => 'h2.news-detail__info__spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'GÜNEŞ',
                'site' => 'http://www.gunes.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h4',
                'off_limit' => 10,
            ],
            [
                'name' => 'SABAH',
                'site' => 'https://www.sabah.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar|album))([a-z0-9-]{4,24}\/)?([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.pageTitle',
                'selector_description' => 'h2.spot',
                'off_limit' => 255,
            ],
            [
                'name' => 'GAZETEKARINCA',
                'site' => 'http://gazetekarinca.com',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/([a-z0-9-]{24,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => 'h4',
                'off_limit' => 255,
            ],
            [
                'name' => 'HTHAYAT',
                'site' => 'https://hthayat.haberturk.com',
                'base' => '/',
                'url_pattern' => '(\b(?!blog))([a-z0-9-]{4,24})\/haber\/\d{7,9}-([a-z0-9-]{4,24})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'ETKİHABER',
                'site' => 'http://www.etkihaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{10,128})-(\d{6,9})h\.htm',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
            [
                'name' => 'GZT',
                'site' => 'https://www.gzt.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'off_limit' => 255,
            ],
            [
                'name' => 'MEMUR ATAMALARI',
                'site' => 'http://www.memuratamalari.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{4,9})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'off_limit' => 255,
            ],
        ];

        foreach ($items as $item)
        {
            $query = MediaCrawler::updateOrCreate(
                [
                    'name' => $item['name']
                ],
                [
                    'site' => $item['site'],
                    'base' => $item['base'],
                    'url_pattern' => $item['url_pattern'],
                    'selector_title' => $item['selector_title'],
                    'selector_description' => $item['selector_description'],
                    'off_limit' => $item['off_limit']
                ]
            );
        }
    }
}