<?php

use Illuminate\Database\Seeder;
use App\Models\Crawlers\MediaCrawler;

class MediaCrawlersTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $items = [
            [
                'name' => 'DÜNYA',
                'site' => 'https://www.dunya.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-haberi-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 10,
            ],
            [
                'name' => 'HABER7',
                'site' => 'http://www.haber7.com',
                'base' => '/',
                'url_pattern' => '(\b(?!advertorial|yazarlar))([a-z0-9-]{4,24})\/haber\/(\d{7,9})-([a-z0-9-]{4,128})',
                'selector_title' => 'h1.title',
                'selector_description' => 'h2.spot',
                'control_interval' => 5,
            ],
            [
                'name' => 'MYNET SPOR',
                'site' => 'https://www.mynet.com',
                'base' => 'spor',
                'url_pattern' => '([a-z0-9-]{10,128})-(\d{6,9})-myspor',
                'selector_title' => 'h1.detail-post-title',
                'selector_description' => 'h2.detail-post-spot',
                'control_interval' => 15,
            ],
            [
                'name' => 'ULUSAL KANAL',
                'site' => 'http://www.ulusalkanal.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{6,9})\.html',
                'selector_title' => 'h2',
                'selector_description' => 'h3',
                'control_interval' => 15,
            ],
            [
                'name' => 'MİLAT GAZETESİ',
                'site' => 'https://www.milatgazetesi.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})([a-z0-9-]{4,24})\/haber-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'p.spot',
                'control_interval' => 10,
            ],
            [
                'name' => 'HÜR HABER',
                'site' => 'http://www.hurhaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.dsag > h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'ÖNCE VATAN',
                'site' => 'https://www.oncevatan.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{6,9})\.html',
                'selector_title' => 'h3.title',
                'selector_description' => 'p.lead',
                'control_interval' => 15,
            ],
            [
                'name' => 'GERÇEK GÜNDEM',
                'site' => 'http://www.gercekgundem.com',
                'base' => '/',
                'url_pattern' => '(\b(?!posts))([a-z0-9-]{4,128})\/(\d{5,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.article-title',
                'selector_description' => '.article-excerpt',
                'control_interval' => 10,
            ],
            [
                'name' => 'EUROVİZYON',
                'site' => 'http://www.eurovizyon.co.uk',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{5,9})\.html',
                'selector_title' => '.panel-title h1',
                'selector_description' => '.panel-title p',
                'control_interval' => 10,
            ],
            [
                'name' => 'FOTOMAÇ',
                'site' => 'https://www.fotomac.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=href="\/(?!album))([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1#NewsTitle',
                'selector_description' => 'h2#NewsSpot',
                'control_interval' => 10,
            ],
            [
                'name' => 'DOĞRU HABER',
                'site' => 'https://dogruhaber.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{6,9})-([a-z0-9-]{4,128})\/',
                'selector_title' => 'h1',
                'selector_description' => 'article > p:first-child',
                'control_interval' => 15,
            ],
            [
                'name' => 'SON SÖZ',
                'site' => 'https://sonsoz.com.tr',
                'base' => 'feed',
                'url_pattern' => '([a-z0-9-]{24,128})(?=\/)',
                'selector_title' => 'h1.entry-title',
                'selector_description' => 'h2',
                'control_interval' => 30,
            ],
            [
                'name' => 'FUTBOL SAYFASI',
                'site' => 'https://www.futbolsayfasi.net',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{5,9})\.html',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 30,
            ],
            [
                'name' => 'T24',
                'site' => 'http://t24.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})\,(\d{6,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.top-context > h2',
                'control_interval' => 5,
            ],
            [
                'name' => 'URFANATİK',
                'site' => 'http://www.urfanatik.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{5,9})\.html',
                'selector_title' => 'h1',
                'selector_description' => 'p.lead',
                'control_interval' => 15,
            ],
            [
                'name' => 'PRESS HABER',
                'site' => 'http://www.presshaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{5,9})\.html',
                'selector_title' => 'h1.baslik',
                'selector_description' => '.content > p:first-child',
                'control_interval' => 30,
            ],
            [
                'name' => 'TAKVİM',
                'site' => 'https://www.takvim.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{10,128})',
                'selector_title' => 'h1#haberTitle',
                'selector_description' => 'h2#haberSpot',
                'control_interval' => 20,
            ],
            [
                'name' => 'EVRENSEL',
                'site' => 'https://www.evrensel.net',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{6,9})\/([a-z0-9-]{4,128})',
                'selector_title' => '.article-header > h1',
                'selector_description' => '.spot > h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'YENİ AKİT',
                'site' => 'http://www.yeniakit.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 5,
            ],
            [
                'name' => 'TIMETURK',
                'site' => 'https://www.timeturk.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})\/haber-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 5,
            ],
            [
                'name' => 'PLATFORM 24',
                'site' => 'http://platform24.org',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h3.hNewTitle',
                'selector_description' => 'h3.hNewsSubTitle',
                'control_interval' => 45,
            ],
            [
                'name' => 'SON SAYFA',
                'site' => 'http://www.sonsayfa.com',
                'base' => '/',
                'url_pattern' => 'Haberler\/([a-zA-Z0-9-]{4,24})\/([a-zA-Z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => '.news-detail h2',
                'selector_description' => '.news-detail p.brief',
                'control_interval' => 45,
            ],
            [
                'name' => 'ANAYURT GAZETESİ',
                'site' => 'http://www.anayurtgazetesi.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-zA-Z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 45,
            ],
            [
                'name' => 'AKŞAM',
                'site' => 'http://www.aksam.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})\/haber-(\d{6,9})',
                'selector_title' => '.newsdetailwrap h1',
                'selector_description' => '.newsdetailwrap h2',
                'control_interval' => 5,
            ],
            [
                'name' => 'POSTA',
                'site' => 'http://www.posta.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})(-(\b(?!video)))?-(\d{7,9})',
                'selector_title' => 'h1.news-detail__info__title',
                'selector_description' => 'h2.news-detail__info__spot',
                'control_interval' => 5,
            ],
            [
                'name' => 'SABAH',
                'site' => 'https://www.sabah.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar|album))([a-z0-9-]{4,24}\/)?([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.pageTitle',
                'selector_description' => 'h2.spot',
                'control_interval' => 10,
            ],
            [
                'name' => 'ODATV',
                'site' => 'https://www.odatv.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{7,9})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'control_interval' => 10,
            ],
            [
                'name' => 'KAMU AJANS',
                'site' => 'http://www.kamuajans.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{10,128})-h(\d{6,9})\.html',
                'selector_title' => 'h1',
                'selector_description' => 'h2[itemprop="description"]',
                'control_interval' => 15,
            ],
            [
                'name' => 'GAZETECİLER',
                'site' => 'http://www.gazeteciler.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'YENİ MESAJ',
                'site' => 'http://www.yenimesaj.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-H(\d{6,9})\.htm',
                'selector_title' => 'h1.h1',
                'selector_description' => '.haber > div:nth-child(2)',
                'control_interval' => 15,
            ],
            [
                'name' => 'HTKULÜP',
                'site' => 'https://htkulup.haberturk.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/haber\/(\d{7,9})-([a-z0-9-]{10,128})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 20,
            ],
            [
                'name' => 'GİRİŞİM HABER',
                'site' => 'http://www.girisimhaber.com',
                'base' => '/',
                'url_pattern' => 'post\/(\d{4})\/(\d{2})\/(\d{2})\/([a-zA-Z0-9-]{4,128})\.aspx',
                'selector_title' => '#post_title',
                'selector_description' => '#entry p',
                'control_interval' => 30,
            ],
            [
                'name' => 'SOL',
                'site' => 'http://haber.sol.org.tr',
                'base' => 'anasayfa',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1#page-title',
                'selector_description' => '.singlenews-spot',
                'control_interval' => 15,
            ],
            [
                'name' => 'BLOOMBERGHT',
                'site' => 'https://www.bloomberght.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/haber\/\d{7,9}-([a-z0-9-]{4,24})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'TÜRKİYE HABER AJANSI',
                'site' => 'http://www.turkiyehaberajansi.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 10,
            ],
            [
                'name' => 'MEDYA FARESİ',
                'site' => 'http://www.medyafaresi.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => '.news > h1',
                'selector_description' => '.news > h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'OCAK MEDYA',
                'site' => 'http://www.ocakmedya.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.td-post-content > p:first-child',
                'control_interval' => 15,
            ],
            [
                'name' => 'TÜRKİYE GAZETESİ',
                'site' => 'http://www.turkiyegazetesi.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar))([a-z0-9-]{4,24})\/(\d{6,9})\.aspx',
                'selector_title' => 'h1',
                'selector_description' => 'h2.article_abstract',
                'control_interval' => 5,
            ],
            [
                'name' => 'YAKIN PLAN',
                'site' => 'https://yakinplan.com',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.td-post-content > p:first-child',
                'control_interval' => 45,
            ],
            [
                'name' => 'EURONEWS',
                'site' => 'https://tr.euronews.com',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => '.c-article-content',
                'control_interval' => 5,
            ],
            [
                'name' => 'GAZETE DUVAR',
                'site' => 'https://www.gazeteduvar.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => '.single-post h2',
                'selector_description' => 'span.subtitle',
                'control_interval' => 10,
            ],
            [
                'name' => 'BEYAZ GAZETE',
                'site' => 'http://beyazgazete.com',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{4})\/(\d{1,2})\/(\d{1,2})\/([a-z0-9-]{4,128})-(\d{7,9})\.html',
                'selector_title' => 'h1.title',
                'selector_description' => 'p.description',
                'control_interval' => 15,
            ],
            [
                'name' => 'BİANET',
                'site' => 'http://bianet.org',
                'base' => '/',
                'url_pattern' => 'bianet\/([a-z0-9-]{4,128})\/(\d{6,9})-([a-z0-9-]{4,128})',
                'selector_title' => '.post_text_container > a',
                'selector_description' => '.desc',
                'control_interval' => 10,
            ],
            [
                'name' => 'KARAR',
                'site' => 'http://www.karar.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1.title',
                'selector_description' => 'h2[itemprop="description"]',
                'control_interval' => 5,
            ],
            [
                'name' => 'RUDAW',
                'site' => 'http://www.rudaw.net',
                'base' => 'Turkish',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,24})\/(\d{9,10})',
                'selector_title' => 'h3.articleTitle',
                'selector_description' => '.textContent > p:first-child',
                'control_interval' => 10,
            ],
            [
                'name' => 'İHA',
                'site' => 'http://www.iha.com.tr',
                'base' => '/',
                'url_pattern' => 'haber-([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 5,
            ],
            [
                'name' => 'ONEDİO',
                'site' => 'https://onedio.com',
                'base' => 'haberler',
                'url_pattern' => 'haber\/([a-z0-9-]{10,128})-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => '.text > h3',
                'control_interval' => 20,
            ],
            [
                'name' => 'CHIP',
                'site' => 'https://www.chip.com.tr',
                'base' => 'haber',
                'url_pattern' => 'haber\/([a-z0-9-]{10,128})_(\d{5,9})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'p[itemprop="description"]',
                'control_interval' => 30,
            ],
            [
                'name' => 'İNTERNET HABER',
                'site' => 'http://www.internethaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{7,9})h\.htm',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 10,
            ],
            [
                'name' => 'ETKİ HABER',
                'site' => 'http://www.etkihaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{10,128})-(\d{6,9})h\.htm',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'control_interval' => 15,
            ],
            [
                'name' => 'KHA',
                'site' => 'http://www.kha.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{5,9})h\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2.page-summary',
                'control_interval' => 10,
            ],
            [
                'name' => 'İLERİ HABER',
                'site' => 'http://ilerihaber.org',
                'base' => '/',
                'url_pattern' => 'icerik\/([a-z0-9-]{10,128})-(\d{5,9})\.html',
                'selector_title' => '.waypoint > h1',
                'selector_description' => '.waypoint > h2.spot',
                'control_interval' => 15,
            ],
            [
                'name' => 'YENİ ASYA',
                'site' => 'http://www.yeniasya.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!video|yazar))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})_(\d{6,9})',
                'selector_title' => '.head > h2',
                'selector_description' => '.details > .intro',
                'control_interval' => 15,
            ],
            [
                'name' => 'HABERLER',
                'site' => 'https://www.haberler.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{8,9})-haberi',
                'selector_title' => 'h1#haber_baslik',
                'selector_description' => 'h2.spot',
                'control_interval' => 10,
            ],
            [
                'name' => 'SENİN MEDYAN',
                'site' => 'https://seninmedyan.org',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.td-post-content p',
                'control_interval' => 15,
            ],
            [
                'name' => 'MEPANEWS',
                'site' => 'https://www.mepanews.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{10,128})-(\d{5,9})h\.htm',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'control_interval' => 15,
            ],
            [
                'name' => 'HABER TÜRK',
                'site' => 'http://www.haberturk.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{2,128})-(\d{7,8})(-[a-z0-9-]{2,24})?',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 5,
            ],
            [
                'name' => 'PRESS TÜRK',
                'site' => 'http://www.pressturk.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})\/(\d{5,9})',
                'selector_title' => '.haber-detay > div:nth-child(2)',
                'selector_description' => '.haber-detay > div:nth-child(3)',
                'control_interval' => 15,
            ],
            [
                'name' => 'OBJEKTİF HABER',
                'site' => 'http://www.objektifhaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{6,9})-haber',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'p[itemprop="description"]',
                'control_interval' => 15,
            ],
            [
                'name' => 'GAZETE KARINCA',
                'site' => 'http://gazetekarinca.com',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/([a-z0-9-]{24,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => 'h4',
                'control_interval' => 15,
            ],
            [
                'name' => 'DEMOKRAT HABER',
                'site' => 'https://www.demokrathaber.org',
                'base' => '/',
                'url_pattern' => '(\b(?!tarih))([a-z0-9-]{4,24})\/([a-z0-9-]{10,128})-h(\d{6,9})\.html',
                'selector_title' => '.panel-title > h1',
                'selector_description' => '.panel-title > p',
                'control_interval' => 15,
            ],
            [
                'name' => 'ANADOLU GAZETESİ',
                'site' => 'http://www.anadolugazetesi.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{10,128})-(\d{6,9})\.html',
                'selector_title' => '.Baslik > h1',
                'selector_description' => '.ozet > h2',
                'control_interval' => 20,
            ],
            [
                'name' => 'YURT GAZETESİ',
                'site' => 'http://www.yurtgazetesi.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{5,9})\.html',
                'selector_title' => 'h3.title',
                'selector_description' => 'p.lead',
                'control_interval' => 20,
            ],
            [
                'name' => 'FANATİK',
                'site' => 'https://www.fanatik.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar))([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1.news-detail__info__title',
                'selector_description' => 'h2.news-detail__info__spot',
                'control_interval' => 20,
            ],
            [
                'name' => 'AHABER',
                'site' => 'https://www.ahaber.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=href="\/)([a-z0-9-]{4,24})\/\d{4}\/\d{2}\/\d{2}\/([a-z0-9-]{4,128})',
                'selector_title' => '.detailLeftFrame h1',
                'selector_description' => '.detailLeftFrame h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'GAZETE NE HABER',
                'site' => 'http://www.gazetenehaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})\/(\d{5,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2.spot',
                'control_interval' => 20,
            ],
            [
                'name' => 'WEBTEKNO',
                'site' => 'http://www.webtekno.com',
                'base' => 'haber',
                'url_pattern' => '([a-z0-9-]{10,128})-h(\d{5,9})\.html',
                'selector_title' => 'h1[itemprop="headline"] a',
                'selector_description' => '[itemprop="description"]',
                'control_interval' => 30,
            ],
            [
                'name' => 'NTV',
                'site' => 'https://www.ntv.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=href="\/)([a-z0-9-]{4,24})\/([a-z0-9-]{4,128}),([a-zA-Z0-9-_]{22})(?=")',
                'selector_title' => 'h1',
                'selector_description' => 'article > h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'HABER GAZETESİ',
                'site' => 'http://www.habergazetesi.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{7,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'TGRT HABER',
                'site' => 'http://www.tgrthaber.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!fotogaleri))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})(?=")',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2.haber-spot',
                'control_interval' => 15,
            ],
            [
                'name' => 'TÜRKTIME',
                'site' => 'http://www.turktime.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})\/(\d{6,9})',
                'selector_title' => '#haberdetaybaslik > h1',
                'selector_description' => '#haberdetaybaslik > h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'SPUTNIKNEWS',
                'site' => 'https://tr.sputniknews.com',
                'base' => '/',
                'url_pattern' => '(\b(?!infografik))([a-z0-9_-]{4,24})\/\d{4}\d{2}\d{2}(\d{10})-([a-z0-9-]{10,128})',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '.b-article__lead > p',
                'control_interval' => 15,
            ],
            [
                'name' => 'HTHAYAT',
                'site' => 'https://hthayat.haberturk.com',
                'base' => '/',
                'url_pattern' => '(\b(?!blog))([a-z0-9-]{4,24})\/haber\/\d{7,9}-([a-z0-9-]{4,24})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 20,
            ],
            [
                'name' => 'DİKEN',
                'site' => 'http://www.diken.com.tr',
                'base' => '/',
                'url_pattern' => '(?<=\.com.tr\/)([a-z0-9-]{16,})(?=\/)',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.entry-content > p:first-child',
                'control_interval' => 15,
            ],
            [
                'name' => 'HABER VAKTİM',
                'site' => 'https://www.habervaktim.com',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{6,9})\/([a-z0-9-]{4,128})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '.short_content',
                'control_interval' => 15,
            ],
            [
                'name' => 'BBC',
                'site' => 'https://www.bbc.com',
                'base' => 'turkce',
                'url_pattern' => '(\b(?!gettyimages|-))turkce\/([a-z0-9-]{10,128})-(\d{8,9})',
                'selector_title' => 'h1.story-body__h1',
                'selector_description' => 'p.story-body__introduction',
                'control_interval' => 15,
            ],
            [
                'name' => 'DÖVİZ',
                'site' => 'https://haber.doviz.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{10,128})\/(\d{6,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.left-column p',
                'control_interval' => 15,
            ],
            [
                'name' => 'BİRGÜN',
                'site' => 'https://www.birgun.net',
                'base' => '/',
                'url_pattern' => 'haber-detay\/([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'article.haber-detay .title',
                'selector_description' => '.body > p:first-child',
                'control_interval' => 15,
            ],
            [
                'name' => 'ASPOR',
                'site' => 'https://www.aspor.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'SÖZCÜ',
                'site' => 'https://www.sozcu.com.tr',
                'base' => '/',
                'url_pattern' => '(\d{4})\/([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'AJANS HABER',
                'site' => 'http://www.ajanshaber.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-haber-(\d{6,9})',
                'selector_title' => 'header > h1',
                'selector_description' => 'header > h2',
                'control_interval' => 15,
            ],
            [
                'name' => 'AA',
                'site' => 'https://www.aa.com.tr',
                'base' => 'tr',
                'url_pattern' => 'tr\/([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})\/(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => '.lead',
                'control_interval' => 10,
            ],
            [
                'name' => 'SPORX',
                'site' => 'http://www.sporx.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{10,128})-([A-Z0-9]){14}',
                'selector_title' => 'h1#habertitle',
                'selector_description' => 'h2#haberheadline',
                'control_interval' => 15,
            ],
            [
                'name' => 'YENİ ÇAĞ',
                'site' => 'http://www.yenicaggazetesi.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{6,9})h\.htm',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '[itemprop="description"]',
                'control_interval' => 10,
            ],
            [
                'name' => 'STAR',
                'site' => 'http://www.star.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-haber-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 5,
            ],
            [
                'name' => 'MYNET HABER',
                'site' => 'http://www.mynet.com',
                'base' => 'haber',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{10,12})',
                'selector_title' => 'h1.detail-post-title',
                'selector_description' => 'h2.detail-post-spot',
                'control_interval' => 10,
            ],
            [
                'name' => 'TRT HABER',
                'site' => 'http://www.trthaber.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'p[itemprop="description"]',
                'control_interval' => 5,
            ],
            [
                'name' => 'CUMHURİYET',
                'site' => 'http://www.cumhuriyet.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,24})\/(\d{7,9})\/([a-zA-Z0-9-_]{4,128})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '.news-short',
                'control_interval' => 30,
            ],
            [
                'name' => 'NETGAZETE',
                'site' => 'http://www.netgazete.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})(?=")',
                'selector_title' => 'h1',
                'selector_description' => 'p',
                'control_interval' => 10,
            ],
            [
                'name' => 'F5HABER',
                'site' => 'https://www.f5haber.com',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar|yazar))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 1,
            ],
            [
                'name' => 'SONDAKİKA',
                'site' => 'https://www.sondakika.com',
                'base' => '/',
                'url_pattern' => 'haber\/([a-z0-9-]{4,128})-(\d{8,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2[itemprop="description"]',
                'control_interval' => 10,
            ],
            [
                'name' => 'MİLLİYET',
                'site' => 'http://www.milliyet.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar|album))([a-z0-9-]{4,128})-(\d{7,9})(?=\/)',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 5,
            ],
            [
                'name' => 'HÜRRİYET',
                'site' => 'http://www.hurriyet.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{8,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 1,
            ],
            [
                'name' => 'ENSONHABER',
                'site' => 'http://www.ensonhaber.com',
                'base' => '/',
                'url_pattern' => '((?!.*-kimdir)[a-z0-9-]{10,128})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => 'h2[itemprop="description"]',
                'control_interval' => 10,
            ],
            [
                'name' => 'CNNTÜRK',
                'site' => 'https://www.cnnturk.com',
                'base' => '/',
                'url_pattern' => '(?<=href="\/)([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})(?=")',
                'selector_title' => 'h1.detail-title',
                'selector_description' => 'h2.detail-description',
                'control_interval' => 10,
            ],
            [
                'name' => 'MEDYA RADAR',
                'site' => 'http://www.medyaradar.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{16,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2',
                'control_interval' => 20,
            ],
            [
                'name' => 'YENİ ŞAFAK',
                'site' => 'https://www.yenisafak.com',
                'base' => '/',
                'url_pattern' => '(\b(?!yazarlar))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h2.spot',
                'control_interval' => 15,
            ],
            [
                'name' => 'DHA',
                'site' => 'https://www.dha.com.tr',
                'base' => '/',
                'url_pattern' => '(\b(?!foto-galeri|video|english))([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})\/haber-(\d{7,9})',
                'selector_title' => 'h1',
                'selector_description' => '.news-body > p.spot',
                'control_interval' => 10,
            ],
            [
                'name' => 'GAZETE YENİ YÜZYIL',
                'site' => 'http://www.gazeteyeniyuzyil.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-h(\d{6,9})\.html',
                'selector_title' => 'h3.title',
                'selector_description' => 'p.lead',
                'control_interval' => 1,
            ],
            [
                'name' => 'MİLLİ GAZETE',
                'site' => 'https://www.milligazete.com.tr',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{7,9})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'p[itemprop="description"]',
                'control_interval' => 10,
            ],
            [
                'name' => 'HABER3',
                'site' => 'https://www.haber3.com',
                'base' => '/',
                'url_pattern' => '(\b(?!foto-galeri))([a-z0-9-]{4,24}\/)?([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{7,9})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2',
                'control_interval' => 10,
            ],
            [
                'name' => 'AYDINLIK',
                'site' => 'https://www.aydinlik.com.tr',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-([a-z0-9-]{4,24})([a-z0-9-]{4,24})(\d{4})([-]\d{1})',
                'selector_title' => 'h1.author_title',
                'selector_description' => '.white p:nth-child(2)',
                'control_interval' => 20,
            ],
            [
                'name' => 'GAZETE VATAN',
                'site' => 'http://www.gazetevatan.com',
                'base' => '/',
                'url_pattern' => '((?!.*yazar-yazisi)[a-z0-9-]{4,128})-(\d{7,9})-([a-z0-9-]{4,24})',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => 'h2[itemprop="description"]',
                'control_interval' => 10,
            ],
            [
                'name' => 'HABERİ YAKALA',
                'site' => 'http://www.haberiyakala.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{6,9})-haber',
                'selector_title' => 'h1.news-title',
                'selector_description' => 'h2.news-desc',
                'control_interval' => 10,
            ],
            [
                'name' => 'MEDYALOJİ',
                'site' => 'https://www.medyaloji.net',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})_(\d{8,9})\.html',
                'selector_title' => 'h1[itemprop="name"]',
                'selector_description' => '.articleTitle > div',
                'control_interval' => 10,
            ],
            [
                'name' => 'BIGPARA',
                'site' => 'http://bigpara.hurriyet.com.tr',
                'base' => '/',
                'url_pattern' => 'haberler\/([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})_ID(\d{7,9})',
                'selector_title' => 'h1.news-detail-title',
                'selector_description' => '.tag-content > p:first-child',
                'control_interval' => 10,
            ],
            [
                'name' => 'GÜNEŞ',
                'site' => 'http://www.gunes.com',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,24})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1',
                'selector_description' => 'h4',
                'control_interval' => 10,
            ],
            [
                'name' => 'ORTADOĞU GAZETESİ',
                'site' => 'http://www.ortadogugazetesi.net',
                'base' => '/',
                'url_pattern' => '([a-z0-9-]{4,128})-(\d{5,9})\.html',
                'selector_title' => '.content h1',
                'selector_description' => '.content strong:first-child',
                'control_interval' => 10,
            ],
            [
                'name' => 'GAZETE PORT',
                'site' => 'http://gazeteport.com',
                'base' => '/',
                'url_pattern' => '(\d{4})\/([a-z0-9-]{4,128})-(\d{6,9})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => '.entry p:first-child',
                'control_interval' => 10,
            ],
            [
                'name' => 'MEMURLAR',
                'site' => 'https://www.memurlar.net',
                'base' => '/',
                'url_pattern' => 'haber\/(\d{6,9})\/([a-z0-9-]{4,128})\.html',
                'selector_title' => 'h1[itemprop="headline"]',
                'selector_description' => '[itemprop="description"]',
                'control_interval' => 10,
            ],
            [
                'name' => 'JURNAL',
                'site' => 'http://www.jurnal.net',
                'base' => '/',
                'url_pattern' => '(\d{4})\/(\d{2})\/(\d{2})\/([a-z0-9-]{4,128})',
                'selector_title' => 'h1.entry-title',
                'selector_description' => 'blockquote',
                'control_interval' => 30,
            ],
        ];

        foreach ($items as $item)
        {
            $query = MediaCrawler::updateOrCreate(
                [
                    'name' => $item['name']
                ],
                [
                    'site' => $item['site'],
                    'base' => $item['base'],
                    'url_pattern' => $item['url_pattern'],
                    'selector_title' => $item['selector_title'],
                    'selector_description' => $item['selector_description'],
                    'control_interval' => $item['control_interval']
                ]
            );
        }
    }
}