<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="([a-z0-9-]{4,24})">KEYWORD</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="([a-z0-9-]{4,128})">SLUG</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="\/">/</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="-">-</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="\.">.</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="(\d{5,9})">d{5,9}</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="(\d{6,9})">d{6,9}</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="(\d{4})">d{4}</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="(\d{2})">d{2}</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="\.htm">.htm</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="\.html">.html</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern='(?<=href\="\/)'>(?<=href\="\/)</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern='(?=")'>(?=")</a>
<a style="padding: 0 .4rem;" href="#" data-id="match" data-pattern="(\b(?!yazarlar))">(\b(?!yazarlar))</a>
